language: node_js
node_js:
  - "7"

after_install: npm test

script: npm run dist

deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  
git:
  depth: 3
